name: The Beastie Blog
timezone: America/Chicago
permalink: pretty
highlighter: rouge
lsi: false
paginate: 20
markdown: kramdown
rdiscount:
  extensions:
    - smart
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-coffeescript
gist:
  noscript: false
owner:
  long_name: Lawrence "The BSD Dreamer" Chen
  name: Lawrence "The Dreamer" Chen
  gravatar: 46c4c604abcf0a670346206dc9608a7e
  email: beastie@tardisi.com
  twitter: LawrenceChen
  blog: http://lawrencechen.net
  gallery: http://tardisi.com
  apn: http://apnarcoplexic.com
  github: TheDreamer
# Since GH overrides this, use to detect testing
safe: false
